version: '2'
services:
 landing:
   image: httpd:2.4
   volumes:
    - ./landing_page:/usr/local/apache2/htdocs/
   ports:
    - "80:80"

 web:
   image: vulhub/appweb:7.0.1
   volumes:
    - ./app_server/appweb.conf:/etc/appweb/appweb.conf
    - ./app_server/src:/var/www/appweb
   ports:
    - "8081:8080"

 nginx:
   image: nginx:1
   volumes:
    - ./php/src:/usr/share/nginx/html
    - ./php/src/default.conf:/etc/nginx/conf.d/default.conf
   depends_on:
    - php
   ports:
    - "8080:80"
 php:
   image: php:7.2.10-fpm
   volumes:
    - ./php/src:/var/www/html
    - ./php/creds.txt:/creds.txt

 vm1:
   build: ./ssh_server/vm1
   ports:
     - "2222:22"
   volumes:
     - ./ssh_server/vm1/sshd_config:/etc/ssh/sshd_config
   command: bash -c "service ssh start | tail -f /dev/null"

 vm2:
   build: ./ssh_server/vm2
   ports:
     - "2223:22"
   volumes:
     - ./ssh_server/vm1/sshd_config:/etc/ssh/sshd_config
   command: bash -c "service ssh start | tail -f /dev/null"

 vm3:
   build: ./ssh_server/vm3
   ports:
     - "2224:22"
   volumes:
     - ./ssh_server/vm1/sshd_config:/etc/ssh/sshd_config
   command: bash -c "service ssh start | tail -f /dev/null"
